CREATE TABLE PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL ,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE INT
);

CREATE TABLE REVIEW (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    RATING INT,
    TITLE VARCHAR(255) NOT NULL,
    BODY VARCHAR(255) NOT NULL,
    PRODUCT_ID INT NOT NULL
);

CREATE TABLE COMMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BODY VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    REVIEW_ID INT NOT NULL
);
